export const providerMissionsSeed = [
  {
    id: 1001,
    service: 'Soins a domicile',
    client_name: 'Amina Diallo',
    address: 'Yaba, Lagos',
    time: '08:30',
    amount: 25000,
    status: 'pending',
    description: 'Visite de routine et suivi post-operatoire.',
    progress: 10,
    assigned_provider: 'FlexiCare Pro',
  },
  {
    id: 1002,
    service: 'Aide a la toilette',
    client_name: 'M. Okafor',
    address: 'Ikeja, Lagos',
    time: '11:00',
    amount: 18000,
    status: 'in_progress',
    description: 'Mission en cours avec assistance quotidienne.',
    progress: 65,
    assigned_provider: 'FlexiCare Pro',
  },
  {
    id: 1003,
    service: 'Soins bebe',
    client_name: 'Sophie Mensah',
    address: 'Victoria Island, Lagos',
    time: '16:00',
    amount: 22000,
    status: 'completed',
    description: 'Mission terminee avec retour client positif.',
    progress: 100,
    assigned_provider: 'FlexiCare Pro',
  },
]

export const earningsSeed = {
  total: 184500,
  today: 32500,
  week: 101000,
  month: 410500,
  history: [
    { id: 1, label: 'Mission #1003', date: '22 Mar 2026', amount: 22000, status: 'completed' },
    { id: 2, label: 'Mission #1002', date: '22 Mar 2026', amount: 18000, status: 'in_progress' },
    { id: 3, label: 'Mission #0999', date: '21 Mar 2026', amount: 36500, status: 'completed' },
  ],
}

export const clientMissionsSeed = [
  {
    id: 201,
    service: 'Soins a domicile',
    address: 'Yaba, Lagos',
    description: 'Suivi medical regulier avec creneau du matin.',
    amount: 25000,
    status: 'pending',
    assigned_provider: 'En attente',
    rating: null,
    progress: 15,
  },
  {
    id: 202,
    service: 'Kinesitherapie',
    address: 'Ikoyi, Lagos',
    description: 'Seance de reeducation avec prestation hebdomadaire.',
    amount: 18000,
    status: 'in_progress',
    assigned_provider: 'Grace A.',
    rating: null,
    progress: 60,
  },
  {
    id: 203,
    service: 'Aide menagere',
    address: 'Lekki, Lagos',
    description: 'Mission recurrente validee et finalisee.',
    amount: 22000,
    status: 'completed',
    assigned_provider: 'Michael O.',
    rating: 5,
    progress: 100,
  },
  {
    id: 204,
    service: 'Visite infirmiere',
    address: 'Surulere, Lagos',
    description: 'Mission annulee apres reprogrammation du client.',
    amount: 14500,
    status: 'cancelled',
    assigned_provider: 'Grace A.',
    rating: null,
    progress: 0,
  },
]
